'use strict';
const $=id=>document.getElementById(id);
let state={},draft=null,selected='',busy=false,traffic=[];
const titles={overview:'Network overview',networks:'Networks & devices',policy:'Firewall & VPN',dns:'DNS laboratory',scenarios:'Failure scenarios',configuration:'Configuration'};
const text=(tag,value,cls='')=>{const el=document.createElement(tag);el.textContent=value;if(cls)el.className=cls;return el;};
const notice=(message,error=false)=>{$('notice').textContent=message;$('notice').className=error?'error':'';};
async function api(path,body){const opts=body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Home-Prototype':'1'},body:JSON.stringify(body)};const response=await fetch(path,opts),data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data;}
const act=fn=>async event=>{event?.preventDefault();try{await fn(event);}catch(e){notice(e.message,true);}};
const rate=v=>v>=1e6?(v/1e6).toFixed(2)+' MB/s':v>=1000?(v/1000).toFixed(1)+' kB/s':Math.round(v||0)+' B/s';
function options(el,values,current){el.replaceChildren();for(const [value,label]of values){const o=text('option',label);o.value=value;el.append(o);}el.value=current;}
function edit(){$('config-editor').value=JSON.stringify(draft,null,2);notice('Draft updated. Preview and apply from Configuration.');}
function select(values,value,fn){const el=document.createElement('select');options(el,values.map(v=>[v,v]),value);el.onchange=()=>fn(el.value);return el;}
function input(value,fn,type='text'){const el=document.createElement('input');el.type=type;el.value=value;el.onchange=()=>fn(type==='number'?Number(el.value):el.value);return el;}
function button(label,fn){const el=text('button',label);el.type='button';el.onclick=act(fn);return el;}
const networks=()=>draft.networks.map(n=>n.id);
function renderConfig(){
 if(!draft)return;$('config-editor').value=JSON.stringify(draft,null,2);const ids=networks();$('network-cards').replaceChildren();
 for(const n of draft.networks){const card=text('article','','network-card');card.append(text('h3',n.id));for(const [field,title,type]of [['name','Name','text'],['subnet','IPv4 subnet','text'],['vlan','VLAN ID','number']]){const label=text('label',title);label.append(input(n[field],v=>{n[field]=v;edit();},type));card.append(label);}const label=text('label','Default action');label.append(select(['block','allow'],n.default_action,v=>{n.default_action=v;edit();}));card.append(label,button('Remove',()=>{draft.networks=draft.networks.filter(x=>x!==n);renderConfig();edit();}));$('network-cards').append(card);}
 $('device-list').replaceChildren();for(const d of draft.devices){const row=text('div','','device');row.append(text('code',d.id),input(d.name,v=>{d.name=v;edit();}),select(ids,d.network,v=>{d.network=v;edit();}),button('Remove',()=>{draft.devices=draft.devices.filter(x=>x!==d);renderConfig();edit();}));$('device-list').append(row);}
 for(const id of ['source','destination','vpn-destination'])options($(id),(id==='destination'?[...ids,'internet']:ids).map(n=>[n,n]),$(id).value||(id==='source'?'guests':'services'));
 $('rules').replaceChildren();draft.rules.forEach((r,i)=>{const row=text('div','','rule');const enabled=document.createElement('input');enabled.type='checkbox';enabled.checked=r.enabled;enabled.setAttribute('aria-label','Enable '+r.id);enabled.onchange=()=>{r.enabled=enabled.checked;edit();};row.append(text('span',String(i+1)),enabled,text('code',r.id),select(['*',...ids],r.source,v=>{r.source=v;edit();}),text('span','→'),select(['*',...ids,'internet'],r.destination,v=>{r.destination=v;edit();}),select(['any','tcp','udp','icmp'],r.protocol,v=>{r.protocol=v;if(v==='any'||v==='icmp')r.port=0;renderConfig();edit();}),input(r.port,v=>{r.port=v;edit();},'number'),select(['allow','block'],r.action,v=>{r.action=v;edit();}),button('↑',()=>{if(i){[draft.rules[i-1],draft.rules[i]]=[r,draft.rules[i-1]];renderConfig();edit();}}),button('Remove',()=>{draft.rules.splice(i,1);renderConfig();edit();}));$('rules').append(row);});
 $('peers').replaceChildren();for(const p of draft.vpn_peers){const row=text('div','','peer'),label=text('label',p.id),enabled=document.createElement('input');enabled.type='checkbox';enabled.checked=p.enabled;enabled.onchange=()=>{p.enabled=enabled.checked;edit();};label.append(enabled);const permissions=input(p.allowed_networks.join(', '),v=>{p.allowed_networks=v.split(',').map(s=>s.trim()).filter(Boolean);edit();});permissions.setAttribute('aria-label','Allowed networks for '+p.id);row.append(label,permissions);$('peers').append(row);}options($('peer'),draft.vpn_peers.map(p=>[p.id,p.id]),draft.vpn_peers[0]?.id);
 $('dns-records').value=JSON.stringify(draft.dns.records,null,2);$('dns-blocked').value=draft.dns.blocked.join('\n');$('dns-allowed').value=draft.dns.allowed.join('\n');
}
function draw(){const canvas=$('traffic'),ctx=canvas.getContext('2d'),w=canvas.clientWidth||600,h=240,r=devicePixelRatio||1;canvas.width=w*r;canvas.height=h*r;ctx.scale(r,r);ctx.clearRect(0,0,w,h);let max=1000;for(const p of traffic)max=Math.max(max,p.download_bps,p.upload_bps);ctx.strokeStyle='#293446';ctx.fillStyle='#9caec5';ctx.font='11px system-ui';for(let i=0;i<5;i++){const y=15+200*i/4;ctx.beginPath();ctx.moveTo(65,y);ctx.lineTo(w,y);ctx.stroke();ctx.fillText(rate(max*(1-i/4)),0,y+4);}for(const [key,color]of [['download_bps','#77e1c2'],['upload_bps','#93a8ff']]){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();let started=false;traffic.forEach((p,i)=>{if(!p.valid){started=false;return;}const x=65+i/Math.max(1,traffic.length-1)*(w-70),y=215-p[key]/max*200;if(started)ctx.lineTo(x,y);else ctx.moveTo(x,y);started=true;});ctx.stroke();}if(!traffic.length)ctx.fillText('Collecting traffic samples…',80,110);$('graph-scale').textContent=traffic.length?new Date(traffic[0].timestamp).toLocaleTimeString()+' — '+new Date(traffic.at(-1).timestamp).toLocaleTimeString():'';}
function renderState(){
 const list=state.interfaces||[];if(!list.some(i=>i.id===selected))selected=(list.find(i=>i.up&&['Wi-Fi','Ethernet'].includes(i.type))||list[0])?.id||'';if(document.activeElement!==$('interface'))options($('interface'),list.map(i=>[i.id,i.name]),selected);
 const current=list.find(i=>i.id===selected);$('download').textContent=current?.rate_valid?rate(current.download_bps):'—';$('upload').textContent=current?.rate_valid?rate(current.upload_bps):'—';$('memory').textContent=state.resources?.memory_bytes?(state.resources.memory_bytes/1048576).toFixed(1)+' MiB':'—';$('cpu').textContent='CPU '+(state.resources?.cpu_one_core_percent||0).toFixed(2)+'% of one core';$('health').textContent=state.health?.status||'unknown';$('dns-health').textContent=state.health?.dns_ok===undefined?'Checks every 30 seconds':state.health.dns_ok?'DNS responding':'DNS check failed';
 $('interface-table').replaceChildren();for(const i of list){const tr=document.createElement('tr');tr.append(text('td',i.name),text('td',i.type),text('td',i.up?'Connected':'Disconnected',i.up?'status-up':'status-down'),text('td',i.addresses.join(', ')||'—'));$('interface-table').append(tr);}
 $('events').replaceChildren();for(const e of [...(state.events||[])].reverse().slice(0,30)){const row=text('div','','event');row.append(text('time',new Date(e.timestamp).toLocaleTimeString()),text('span',e.message),text('em',e.origin));$('events').append(row);}if(!state.events?.length)$('events').append(text('small','No incidents recorded.'));
 const s=state.simulation||{};$('scenario-state').textContent=JSON.stringify(s,null,2);$('sensor-cards').replaceChildren();for(const [label,value,detail]of [['Active WAN',s.active_wan,s.backup_available?'Backup available':'No backup'],['Temperature',s.temperature_c+' °C',s.temperature_state],['Fan',s.fan_rpm+' RPM',s.fan_state],['Power',s.power_w+' W',s.ups_on_battery?'UPS battery · '+s.ups_minutes+' min':'Mains power'],['Certificate',s.certificate_days+' days',s.certificate_state]]){const card=document.createElement('article');card.append(text('span',label),text('strong',value),text('small',detail));$('sensor-cards').append(card);}
 const pending=state.configuration?.pending;$('pending').textContent=pending?'Temporary change active · '+state.configuration.seconds_left+' seconds remaining':'No pending configuration';$('confirm').disabled=!pending;$('rollback').disabled=!pending;
}
async function refresh(){if(busy)return;busy=true;try{state=await api('/api/status');renderState();if(selected){traffic=await api('/api/traffic?id='+encodeURIComponent(selected)+'&range='+$('range').value);draw();}$('connection').textContent='Local service connected';}catch(e){$('connection').textContent='Service unavailable';notice(e.message,true);}finally{busy=false;}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view,nav button').forEach(el=>el.classList.remove('active'));b.classList.add('active');$(b.dataset.view).classList.add('active');$('page-title').textContent=titles[b.dataset.view];if(b.dataset.view==='overview')draw();});
$('interface').onchange=()=>{selected=$('interface').value;refresh();};$('range').onchange=refresh;window.addEventListener('resize',draw);
$('connection-form').onsubmit=act(async()=>{$('policy-result').textContent=JSON.stringify(await api('/api/simulation/connection',{source:$('source').value,destination:$('destination').value,protocol:$('protocol').value,port:Number($('port').value)}),null,2);});
$('vpn-form').onsubmit=act(async()=>{$('vpn-result').textContent=JSON.stringify(await api('/api/simulation/connection',{peer:$('peer').value,destination:$('vpn-destination').value}),null,2);});
$('dns-form').onsubmit=act(async()=>{$('dns-result').textContent=JSON.stringify(await api('/api/dns/test',{name:$('dns-name').value}),null,2);});
$('save-dns').onclick=act(()=>{draft.dns.records=JSON.parse($('dns-records').value);for(const [key,id]of [['blocked','dns-blocked'],['allowed','dns-allowed']])draft.dns[key]=$(id).value.split('\n').map(s=>s.trim().toLowerCase()).filter(Boolean);edit();});
$('add-network').onclick=()=>{let vlan=10;while(draft.networks.some(n=>n.vlan===vlan))vlan+=10;draft.networks.push({id:'network-'+Date.now(),name:'New network',vlan,subnet:'10.77.'+vlan+'.0/24',default_action:'block'});renderConfig();edit();};
$('add-device').onclick=()=>{draft.devices.push({id:'device-'+Date.now(),name:'Example device',network:networks()[0]});renderConfig();edit();};
$('add-rule').onclick=()=>{draft.rules.push({id:'rule-'+Date.now(),source:networks()[0],destination:'services',protocol:'tcp',port:443,action:'allow',enabled:true});renderConfig();edit();};
$('load-config').onclick=act(async()=>{draft=await api('/api/config');renderConfig();notice('Active configuration loaded into draft.');});
$('preview').onclick=act(async()=>{const proposed=JSON.parse($('config-editor').value),result=await api('/api/config/preview',proposed);$('config-result').textContent=JSON.stringify(result,null,2);if(result.valid){draft=proposed;renderConfig();}});
$('apply').onclick=act(async()=>{const proposed=JSON.parse($('config-editor').value);await api('/api/config/apply',proposed);draft=proposed;renderConfig();notice('Temporary configuration applied. Confirm within 60 seconds.');await refresh();});
for(const op of ['confirm','rollback'])$(op).onclick=act(async()=>{await api('/api/config/'+op,{});draft=await api('/api/config');renderConfig();notice('Configuration '+op+' complete.');await refresh();});
$('export').onclick=act(()=>{const content=JSON.stringify(JSON.parse($('config-editor').value),null,2),url=URL.createObjectURL(new Blob([content],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='private-local-config.json';link.click();URL.revokeObjectURL(url);});
document.querySelectorAll('[data-scenario]').forEach(b=>b.onclick=act(async()=>{await api('/api/simulation/scenario',{action:b.dataset.scenario});await refresh();}));
(async()=>{try{draft=await api('/api/config');renderConfig();await refresh();}catch(e){notice(e.message,true);}setInterval(refresh,2000);})();
